spring:
  application:
    name: trainSmart
  web:
    locale: en
    locale-resolver: accept_header
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  mvc:
    problemdetails:
      enabled: true
  config:
    import: optional:classpath:statements.yml
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
  ai:
    retry:
      max-attempts: 3
      backoff:
        initial-interval: 2000ms
        multiplier: 2
        max-interval: 10000ms
      on-client-errors: false
      exclude-on-http-codes: [ 400, 401, 403 ]
      on-http-codes: [ 429, 500, 503, 502, 504 ]
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-4o-mini
          max-tokens: 500
          temperature: 0.0

app:
  gym-provider:
    base-url: https://overpass-api.de/api
  security:
    jwt:
      secret: ${JWT_SECRET}
      access-expiration-ms: 900000
    refresh-token:
      expiration-ms: 2592000000
    verification-token:
      expiration-hours: 24
  mailing:
    base-url: http://localhost:8080
    from: no-reply@trainsmart.com
    reply-to: support@trainsmart.com
    validMimeTypes:
      pdf:
        - application/pdf
        - application/x-pdf
      xls:
        - application/vnd.ms-excel
      xlsx:
        - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
    maxSizeBytes: 10485760
server:
  servlet:
    context-path: /api/v1

management:
  health:
    mail:
      enabled: false
