openapi: 3.0.3
info:
  title: User Management API
  version: 1.0.0
tags:
  - name: Auth
    description: Authentication endpoints
  - name: User
    description: User endpoints

paths:
  /auth/login:
    post:
      tags:
        - Auth
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Successful authentication
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestProblem'
  /auth/refresh-token:
    post:
      tags:
        - Auth
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Token refresh successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Unauthorized access
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedProblem'
        '400':
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestProblem'
  /auth/logout:
    post:
      tags:
        - Auth
      operationId: logout
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
      responses:
        '204':
          description: Successfully logged out
        '401':
          description: Unauthorized request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedProblem'
        '400':
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestProblem'
  /users/password-reset:
    post:
      tags:
        - User
      operationId: resetPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        '204':
          description: Reset password success
        '400':
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestProblem'
  /users/send-verification-link:
    post:
      tags:
        - User
      operationId: sendVerificationLink
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendVerificationLinkRequest'
      responses:
        '204':
          description: Link send for given action (reset password or account activation)
        '400':
          description: Invalid token or verification token type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestProblem'
  /users/activate:
    post:
      tags:
        - User
      operationId: activateAccount
      parameters:
        - name: token
          in: query
          required: true
          description: Activation token
          schema:
            type: string
      responses:
        '200':
          description: Account activated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '400':
          description: Invalid token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestProblem'
        '404':
          description: Token not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundProblem'
  /users/register:
    post:
      tags:
        - User
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
      responses:
        '201':
          description: Registration completed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '400':
          description: Invalid values in request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestProblem'
        '409':
          description: User already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConflictProblem'
  /users/me/delete:
    delete:
      tags:
        - User
      operationId: deleteAccount
      security:
        - bearerAuth: [ ]
      responses:
        '204':
          description: Account deleted
        '401':
          description: Unauthorized access
  /users/me/change-email:
    patch:
      tags:
        - User
      operationId: changeEmail
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeEmailRequest'
      responses:
        '204':
          description: Email changed
        '401':
          description: Unauthorized access
        '400':
          description: Invalid email value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestProblem'
  /users/me/change-password:
    patch:
      tags:
        - User
      operationId: changePassword
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
      responses:
        '204':
          description: Password changed
        '401':
          description: Unauthorized access
        '400':
          description: Invalid password value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestProblem'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Username:
      type: string
      minLength: 1
      example: "john.doe12"
    Password:
      type: string
      minLength: 1
      example: "secret1234"
    Email:
      type: string
      format: email
      minLength: 1
      example: "email@example.com"
    RefreshToken:
      type: string
      minLength: 1
      example: "dGhpcy1pcy1yZWZyZXNo"
    ChangeEmailRequest:
      type: object
      required:
        - previousEmail
        - currentEmail
      properties:
        previousEmail:
          $ref: '#/components/schemas/Email'
        currentEmail:
          type: string
          format: email
          minLength: 1
          example: "newEmail@example.com"
    ChangePasswordRequest:
      type: object
      required:
        - previousPassword
        - currentPassword
      properties:
        previousPassword:
          $ref: '#/components/schemas/Password'
        currentPassword:
          type: string
          minLength: 1
          example: "newSecret1234"
    RegisterUserRequest:
      type: object
      required:
        - username
        - password
        - email
        - role
        - birthDate
      properties:
        username:
          $ref: '#/components/schemas/Username'
        password:
          $ref: '#/components/schemas/Password'
        email:
          $ref: '#/components/schemas/Email'
        role:
          type: string
          enum:
            - ROLE_ADMIN
            - ROLE_USER
          example: "ROLE_ADMIN"
        birthDate:
          type: string
          format: date
          example: "1990-04-05"
    SendVerificationLinkRequest:
      type: object
      required:
        - username
        - tokenType
      properties:
        username:
          $ref: '#/components/schemas/Username'
        tokenType:
          type: string
          enum:
            - ACTIVATION
            - PASSWORD_RESET
          example: "PASSWORD_RESET"
    ResetPasswordRequest:
      type: object
      required:
        - token
        - currentPassword
      properties:
        token:
          $ref: '#/components/schemas/RefreshToken'
        currentPassword:
          $ref: '#/components/schemas/Password'
    UserProfileResponse:
      type: object
      required:
        - username
        - email
        - role
        - disabled
      properties:
        username:
          $ref: '#/components/schemas/Username'
        email:
          $ref: '#/components/schemas/Email'
        role:
          type: string
          enum:
            - ROLE_USER
            - ROLE_ADMIN
          example: "ROLE_USER"
        disabled:
          type: boolean
          example: false
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          $ref: '#/components/schemas/Username'
        password:
          $ref: '#/components/schemas/Password'
    RefreshTokenRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          $ref: '#/components/schemas/RefreshToken'
    LogoutRequest:
      type: object
      required:
        - refreshToken
      properties:
        refreshToken:
          $ref: '#/components/schemas/RefreshToken'
    AuthResponse:
      type: object
      required:
        - accessToken
        - refreshToken
      properties:
        accessToken:
          type: string
          example: "eyJhbGciOieyJhbGciOi"
        refreshToken:
          $ref: '#/components/schemas/RefreshToken'
    ProblemDetail:
      type: object
      required:
        - type
        - title
        - status
        - instance
      properties:
        type:
          type: string
        title:
          type: string
        status:
          type: integer
        instance:
          type: string
          format: uri
    BadRequestProblem:
      allOf:
        - $ref: '#/components/schemas/ProblemDetail'
        - type: object
          additionalProperties:
            type: string
          example:
            type: "about:blank"
            title: "Validation failure"
            status: 400
            instance: "/api/v1/current-endpoint-path"
            username: "size must be between 1 and 2147483647"
            password: "size must be between 1 and 2147483647"
    UnauthorizedProblem:
      allOf:
        - $ref: '#/components/schemas/ProblemDetail'
        - type: object
          additionalProperties:
            type: string
          example:
            type: "about:blank"
            title: "User management exception"
            status: 401
            detail: "Invalid token"
            instance: "/api/v1/current-endpoint-path"
    NotFoundProblem:
      allOf:
        - $ref: '#/components/schemas/ProblemDetail'
        - type: object
          additionalProperties:
            type: string
          example:
            type: "about:blank"
            title: "User management exception"
            status: 404
            detail: "Token not found"
            instance: "/api/v1/current-endpoint-path"
    ConflictProblem:
      allOf:
        - $ref: '#/components/schemas/ProblemDetail'
        - type: object
          additionalProperties:
            type: string
          example:
            type: "about:blank"
            title: "User management exception"
            status: 409
            detail: "User already exists"
            instance: "/api/v1/current-endpoint-path"
