spring:
  test:
    database:
      replace: NONE
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    protocol: smtp

app:
  security:
    jwt:
      secret: 4b617369614c756b6177736b61547261696e536d61727450726f6a656b7432303235
      access-expiration-ms: 900000
    refresh-token:
      expiration-ms: 2592000000
    verification-token:
      expiration-hours: 24
  mailing:
    from: test-from@example.com
    reply-to: test-replyto@example.com
    validMimeTypes:
      pdf:
        - application/pdf
    maxSizeBytes: 10485760
