spring:
  test:
    database:
      replace: NONE
  jpa:
    hibernate:
      ddl-auto: create
  mail:
    protocol: smtp

mailing:
  from: test-from@example.com
  reply-to: test-replyto@example.com
  validMimeTypes:
    pdf:
      - application/pdf
  maxSizeBytes: 10485760
